name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel

    - name: Install core dependencies in order
      run: |
        pip install numpy==1.24.3
        pip install pandas==1.5.3
        pip install scikit-learn==1.4.2
        pip install numba==0.57.1
        pip install llvmlite==0.40.1
        pip install shap==0.44.0
    
    - name: Install remaining requirements
      run: |
        pip install -r tests/requirements.txt
        
    - name: List installed packages
      run: |
        pip freeze
        
    - name: Prepare test environment
      run: |
        mkdir -p temp_models
        cp models/*.joblib temp_models/
      
    - name: Run tests
      env:
        MODEL_PATH: temp_models/rf_model_compressed.joblib
        EXPLAINER_PATH: temp_models/shap_explainer_new.joblib
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python -m pytest tests/ -v